// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title IZKVerifier
 * @notice Interface for on-chain ZK proof verification.
 *
 *         The production implementation is generated by Noir's Solidity UltraHonk
 *         verifier output. To generate it:
 *
 *           cd zk/packages/role_commitment
 *           nargo compile && nargo codegen-verifier
 *
 *           cd ../innocence_proof
 *           nargo compile && nargo codegen-verifier
 *
 *         Deploy the two generated Verifier.sol contracts, then deploy
 *         ZKVerifier (the adapter) and point PlagueGame at it:
 *           game.setZkVerifier(address(adapter));
 *
 * ── Circuits ──────────────────────────────────────────────────────────────────
 *
 *  role_commitment.nr
 *    Private inputs : role, secret
 *    Public outputs : commitment = Poseidon(role, secret)
 *    Constraint     : none beyond the commitment binding
 *    Proving system : UltraHonk — npm pkg: noir-lang/backend_barretenberg UltraHonkBackend
 *
 *  innocence_proof.nr
 *    Private inputs : role, secret, room_id, round_number
 *    Public outputs : commitment = Poseidon(role, secret)
 *                     nullifier  = Poseidon(secret, room_id, round_number)
 *    Constraint     : role == ROLE_CLEAN (0) — infected players cannot satisfy this
 *    Proving system : UltraHonk — npm pkg: noir-lang/backend_barretenberg UltraHonkBackend
 */
interface IZKVerifier {
    /**
     * @param commitment  Poseidon(role, secret) as submitted at startGame.
     * @param proof       UltraHonk proof bytes produced by nargo prove / UltraHonkBackend.
     */
    function verifyRoleCommitment(
        bytes32 commitment,
        bytes calldata proof
    ) external view returns (bool);

    /**
     * @param commitment  Poseidon(role, secret) — must match the stored commitment.
     * @param nullifier   Poseidon(secret, roomId, round) — uniquely prevents replay.
     * @param proof       UltraHonk proof bytes produced by nargo prove / UltraHonkBackend.
     */
    function verifyInnocenceProof(
        bytes32 commitment,
        bytes32 nullifier,
        bytes calldata proof
    ) external view returns (bool);
}
