/**
 * runner.ts — Main bot game loop.
 *
 * Orchestrates N bot wallets playing Zombie Plague autonomously.
 *
 * Lifecycle per cycle:
 *   1. Bot[0] (host) creates a room
 *   2. All bots approve cUSD + join the room
 *   3. All bots connect to backend socket with their playerAddress
 *   4. When room reaches maxPlayers, Bot[0] calls startGame()
 *   5. On game_started: each bot submits their pre-generated role commitment
 *   6. On phase_changed → voting: each alive bot casts a vote
 *   7. On game_ended: disconnect sockets, wait CYCLE_DELAY_MS, repeat
 *
 * Requires: agents/data/bot-proofs.json (generated by `npm run setup`)
 */
import { readFile } from 'fs/promises'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import { io, Socket } from 'socket.io-client'
import { buildBotWallets, BACKEND_URL, STAKE_AMOUNT, CYCLE_DELAY_MS } from './config.js'
import {
  ensureApproval,
  createRoom,
  joinRoom,
  startGame,
  submitRoleCommitment,
  castVote,
  getRoom,
  getRoomStatuses,
} from './chain.js'
import type { BotWallet } from './config.js'
import type { BotProof } from './setup.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const PROOFS_PATH = resolve(__dirname, '../data/bot-proofs.json')

// Phase numbers from the contract (RoundPhase enum)
const PHASE_VOTING = 2

// Room status numbers from the contract (RoomStatus enum)
const ROOM_STARTING = 1
const ROOM_ACTIVE = 2
const ROOM_ENDED = 3

// Player status numbers from the contract (PlayerStatus enum)
const STATUS_INFECTED = 1
const STATUS_ELIMINATED = 2

// ── Zombie-themed chat lines bots send during discussion ──────────────────────
const CHAT_LINES = [
  "I'm definitely clean, check my commitment 🧪",
  'Something feels off about this round...',
  "I haven't seen anyone act suspicious yet.",
  'Who do we trust? Nobody, probably.',
  "The infected are among us — I can feel it.",
  'My symptoms are zero. Purely human here.',
  "Don't look at me like that.",
  "Let's eliminate someone who isn't talking.",
  'The plague spreads through silence.',
  "I'll survive this round. Probably.",
]

function randomLine(): string {
  return CHAT_LINES[Math.floor(Math.random() * CHAT_LINES.length)]
}

// ── Socket helpers ────────────────────────────────────────────────────────────

interface GameEvent {
  type: string
  roomId: string
  payload: Record<string, unknown>
  timestamp: number
}

interface RoomSnapshot {
  roomId: string
  room: {
    status: number
    currentPhase: number
    players: string[]
  }
  players: Array<{ addr: string; status: number; hasVotedThisRound: boolean }>
}

function connectBot(
  bot: BotWallet,
  roomId: bigint,
  handlers: {
    onGameStarted: () => void
    onPhaseChanged: (phase: number) => void
    onInfectionAssigned: () => void
    onGameEnded: () => void
    onSnapshot: (snap: RoomSnapshot) => void
  },
): Socket {
  const socket = io(BACKEND_URL, { transports: ['websocket'] })

  socket.on('connect', () => {
    console.log(`[bot-${bot.index}] Socket connected (${socket.id})`)
    socket.emit('join_room', {
      roomId: roomId.toString(),
      playerAddress: bot.address,
    })
  })

  socket.on('game_event', (event: GameEvent) => {
    if (event.roomId !== roomId.toString()) return

    switch (event.type) {
      case 'game_started':
        handlers.onGameStarted()
        break
      case 'phase_changed':
        handlers.onPhaseChanged(Number(event.payload.phase))
        break
      case 'infection_assigned':
        // Only received by the infected bot's own socket
        handlers.onInfectionAssigned()
        break
      case 'game_ended':
        handlers.onGameEnded()
        break
    }
  })

  socket.on('room_snapshot', (snap: RoomSnapshot) => {
    if (snap.roomId === roomId.toString()) {
      handlers.onSnapshot(snap)
    }
  })

  socket.on('disconnect', (reason: string) => {
    console.log(`[bot-${bot.index}] Socket disconnected: ${reason}`)
  })

  socket.on('connect_error', (err: Error) => {
    console.warn(`[bot-${bot.index}] Socket connect error: ${err.message}`)
  })

  return socket
}

// ── Per-bot state ─────────────────────────────────────────────────────────────

interface BotState {
  bot: BotWallet
  proof: BotProof
  socket: Socket | null
  isInfected: boolean
  hasCommitted: boolean
  votedRound: number          // last round number this bot voted in (0 = none yet)
  votedTargets: Set<string>   // lowercased addresses this bot has voted for (own history)
}

// ── Game cycle ────────────────────────────────────────────────────────────────

async function runCycle(bots: BotWallet[], proofs: BotProof[]): Promise<void> {
  const host = bots[0]
  const maxPlayers = bots.length

  console.log(`\n${'='.repeat(60)}`)
  console.log(`Starting cycle with ${maxPlayers} bots`)
  console.log(`${'='.repeat(60)}`)

  // 1. Ensure all bots have approved cUSD
  console.log('\n[setup] Approving cUSD for all bots...')
  await Promise.all(bots.map(bot => ensureApproval(bot, STAKE_AMOUNT * 10n)))

  // 2. Host creates the room
  console.log('\n[setup] Creating room...')
  const roomId = await createRoom(host, STAKE_AMOUNT, maxPlayers)

  // 3. Other bots join (staggered to avoid nonce conflicts)
  console.log('\n[setup] Joining room...')
  for (let i = 1; i < bots.length; i++) {
    await joinRoom(bots[i], roomId)
    await sleep(1500)
  }

  // 4. Connect all bots to socket and set up state
  const states: BotState[] = bots.map((bot, i) => ({
    bot,
    proof: proofs[i],
    socket: null,
    isInfected: false,
    hasCommitted: false,
    votedRound: 0,
    votedTargets: new Set<string>(),
  }))

  // Host fires startGame once the room is full. Snapshots can arrive repeatedly
  // before the tx mines and flips room status, so guard against duplicate sends
  // (which otherwise collide on the same nonce → "already known"/"nonce too low").
  let startGameSent = false

  // Direct on-chain poll for the Starting status. The backend's discrete
  // `game_started` event (and the snapshots it triggers) can be dropped by the
  // event relay, which would leave every bot waiting and the room auto-refunding
  // after the role-commit timeout. Polling chain state guarantees the shield is
  // submitted regardless of socket delivery.
  let statusPoll: ReturnType<typeof setInterval> | undefined

  // Track resolved game end
  let gameEnded = false
  const gameEndedPromise = new Promise<void>(resolve => {
    // Resolved when the first game_ended event arrives
    const checkDone = () => {
      if (gameEnded) resolve()
    }

    // Submit a bot's role commitment ("shield") exactly once. Triggered from
    // three independent paths so a single dropped signal can't stall the room:
    // the `game_started` socket event, `Starting`-status room snapshots, and the
    // backend-independent on-chain status poll below.
    const commitRole = (state: BotState): void => {
      if (state.hasCommitted) return
      state.hasCommitted = true
      void submitRoleCommitment(
        state.bot,
        roomId,
        state.proof.commitment,
        state.proof.proofHex,
      ).catch(err => {
        state.hasCommitted = false // allow a retry on the next snapshot
        console.warn(`[bot-${state.bot.index}] Commitment failed: ${err.message}`)
      })
    }

    for (const state of states) {
      state.socket = connectBot(state.bot, roomId, {
        onGameStarted: () => {
          commitRole(state)
        },

        onInfectionAssigned: () => {
          state.isInfected = true
          console.log(`[bot-${state.bot.index}] *** INFECTED (patient zero) ***`)
        },

        onPhaseChanged: () => {
          // Voting is driven by the backend-independent chain-status poll below,
          // so no per-event action is needed here.
        },

        onGameEnded: () => {
          gameEnded = true
          checkDone()
        },

        onSnapshot: (snap: RoomSnapshot) => {
          // Host: start game when room is full
          if (
            state.bot.index === 0 &&
            !startGameSent &&
            snap.room.status === 0 && // waiting
            snap.room.players.length >= maxPlayers
          ) {
            startGameSent = true
            void startGame(state.bot, roomId).catch(err => {
              startGameSent = false // allow a retry on genuine failure
              console.warn(`[bot-0] startGame failed: ${err.message}`)
            })
          }

          // Any bot: submit the role commitment ("shield") as soon as the room
          // enters Starting. Reliable fallback for a missed `game_started` event.
          if (snap.room.status === 1 /* starting */) {
            commitRole(state)
          }

          // Send a chat message during discussion phase (occasional)
          if (snap.room.currentPhase === 1 && Math.random() < 0.3) {
            state.socket?.emit('chat_message', {
              roomId: roomId.toString(),
              playerAddress: state.bot.address,
              message: randomLine(),
            })
          }
        },
      })
    }

    // Backend-independent driver: poll chain state and act on it directly so the
    // game never stalls when the backend's socket relay drops events. Submits the
    // shield during Starting, and casts votes during the Voting phase.
    statusPoll = setInterval(async () => {
      try {
        const room = await getRoom(roomId)
        const status = Number(room.status)

        if (status === ROOM_STARTING) {
          for (const state of states) commitRole(state)
          return
        }
        if (status === ROOM_ENDED) {
          // End the cycle from chain state — don't depend on the `game_ended`
          // socket event, which the backend relay can drop (otherwise the cycle
          // blocks on the 20-minute safety timeout before the next game starts).
          if (statusPoll) { clearInterval(statusPoll); statusPoll = undefined }
          gameEnded = true
          checkDone()
          return
        }
        if (status === ROOM_ACTIVE && Number(room.currentPhase) === PHASE_VOTING) {
          const round = Number(room.currentRound)
          const pending = states.filter(s => s.votedRound < round)
          if (pending.length === 0) return

          // Authoritative roster from chain (resilient to dropped snapshots).
          const roster = await getRoomStatuses(roomId)
          const aliveAddrs = roster.filter(p => p.status !== STATUS_ELIMINATED).map(p => p.addr)

          for (const state of pending) {
            const self = state.bot.address.toLowerCase()
            const me = roster.find(p => p.addr === self)
            // Skip bots that are no longer alive (eliminated can't vote).
            if (!me || me.status === STATUS_ELIMINATED) { state.votedRound = round; continue }
            castVoteForBot(state, roomId, round, aliveAddrs, me.status === STATUS_INFECTED)
          }
        }
      } catch {
        // Transient RPC error — retry on the next tick.
      }
    }, 4000)
  })

  // 5. Wait for game to end (with a safety timeout)
  const GAME_TIMEOUT_MS = 20 * 60 * 1000 // 20 minutes max
  await Promise.race([gameEndedPromise, sleep(GAME_TIMEOUT_MS)])

  // 6. Stop the status poll and disconnect all sockets
  if (statusPoll) { clearInterval(statusPoll); statusPoll = undefined }
  for (const state of states) {
    state.socket?.disconnect()
  }

  console.log(`\n[cycle] Game ended. Waiting ${CYCLE_DELAY_MS / 1000}s before next cycle...`)
}

// ── Vote strategy ─────────────────────────────────────────────────────────────

/**
 * Cast a bot's vote for the given round, exactly once.
 *
 * Strategy stays within the game's fair information model — a bot only acts on
 * what it legitimately knows (its own role and its own past votes), never on
 * other players' hidden infection status (which, although readable on-chain, is
 * meant to be secret):
 *   - Clean bots vote for a random living opponent — they have no fair signal to
 *     identify the infected, so uniform-random is the honest baseline.
 *   - Infected bots also target living opponents, but prefer ones they haven't
 *     voted for before. The patient zero's vote doubles as the next infection
 *     target, so spreading to fresh players grows the infected side instead of
 *     wasting the vote on someone already targeted.
 *
 * Candidates are derived from the authoritative on-chain roster, so a bot can
 * never vote for itself or an eliminated player.
 */
function castVoteForBot(
  state: BotState,
  roomId: bigint,
  round: number,
  aliveAddrs: string[],
  ownInfected: boolean,
): void {
  if (state.votedRound >= round) return

  const self = state.bot.address.toLowerCase()
  const candidates = aliveAddrs.filter(addr => addr !== self)
  if (candidates.length === 0) return

  // Infected bots prefer targets they haven't hit yet (spread infection wider);
  // fall back to the full set once every opponent has been targeted.
  let pool = candidates
  if (ownInfected) {
    const fresh = candidates.filter(addr => !state.votedTargets.has(addr))
    if (fresh.length > 0) pool = fresh
  }

  const target = pool[Math.floor(Math.random() * pool.length)] as `0x${string}`

  state.votedRound = round // optimistic guard against double-voting this round
  void castVote(state.bot, roomId, target)
    .then(() => { state.votedTargets.add(target) })
    .catch(err => {
      const msg = err instanceof Error ? err.message : String(err)
      // The contract already recorded the vote — treat as done.
      if (/AlreadyVoted/.test(msg)) { state.votedTargets.add(target); return }
      state.votedRound = round - 1 // allow a retry on the next poll tick
      console.warn(`[bot-${state.bot.index}] Vote failed: ${msg}`)
    })
}

// ── Utilities ─────────────────────────────────────────────────────────────────

function sleep(ms: number): Promise<void> {
  return new Promise(res => setTimeout(res, ms))
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  console.log('\nZombie Plague Bot Runner')
  console.log('========================')
  console.log(`Backend: ${BACKEND_URL}`)
  console.log(`Network: ${process.env.NETWORK ?? 'testnet'}`)

  // Load pre-generated proofs
  let proofs: BotProof[]
  try {
    const raw = await readFile(PROOFS_PATH, 'utf8')
    proofs = JSON.parse(raw) as BotProof[]
    console.log(`Loaded ${proofs.length} pre-generated bot proof(s) from ${PROOFS_PATH}`)
  } catch {
    console.error(`\nFailed to load ${PROOFS_PATH}`)
    console.error('Run `npm run setup` first to generate bot proofs.\n')
    process.exit(1)
  }

  const bots = buildBotWallets()

  if (proofs.length < bots.length) {
    console.error(
      `Proof count (${proofs.length}) < bot count (${bots.length}). Re-run setup.`,
    )
    process.exit(1)
  }

  // Verify proof addresses match wallet addresses
  for (let i = 0; i < bots.length; i++) {
    if (proofs[i].address.toLowerCase() !== bots[i].address.toLowerCase()) {
      console.error(
        `Address mismatch at index ${i}: proof has ${proofs[i].address}, ` +
          `wallet is ${bots[i].address}. Re-run setup.`,
      )
      process.exit(1)
    }
  }

  console.log('\nBot wallets:')
  for (const b of bots) console.log(`  Bot ${b.index + 1}: ${b.address}`)

  // Main loop
  let cycle = 0
  while (true) {
    cycle++
    console.log(`\n[runner] Cycle ${cycle}`)
    try {
      await runCycle(bots, proofs)
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      console.error(`[runner] Cycle ${cycle} error: ${msg}`)
      console.log(`[runner] Retrying in ${CYCLE_DELAY_MS / 1000}s...`)
    }
    await sleep(CYCLE_DELAY_MS)
  }
}

main().catch(err => {
  console.error('Fatal:', err)
  process.exit(1)
})
