/**
 * runner.ts — Bot pool manager.
 *
 * The 5 bot wallets form a shared pool that humans can pull from to try the
 * game. The manager:
 *
 *   1. Heartbeats availability to the backend so the lobby shows "K bots free".
 *   2. Drains human "add bots" requests and sends idle bots into those rooms.
 *   3. When ALL bots are idle with no human demand for SELF_PLAY_IDLE_MS, starts
 *      a self-play game so on-chain activity never goes silent.
 *
 * Every game-critical action (role commitment, voting, end detection) is driven
 * by polling chain state — never by socket events, which the backend relay can
 * drop. Sockets are used best-effort for chat/presence only.
 *
 * Requires: agents/data/bot-proofs.json (generated by `npm run setup`)
 */
import { readFile } from 'fs/promises'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import { io, Socket } from 'socket.io-client'
import {
  buildBotWallets,
  BACKEND_URL,
  STAKE_AMOUNT,
  BOT_MAX_STAKE_WEI,
  SELF_PLAY_IDLE_MS,
  SELF_PLAY_DISABLED,
  BOT_RUNNER_SECRET,
} from './config.js'
import {
  ensureApproval,
  createRoom,
  joinRoom,
  startGame,
  submitRoleCommitment,
  castVote,
  getRoom,
  getRoomStatuses,
  hasRoomCapacity,
} from './chain.js'
import type { BotWallet } from './config.js'
import type { BotProof } from './setup.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const PROOFS_PATH = resolve(__dirname, '../data/bot-proofs.json')

// RoomStatus enum
const ROOM_WAITING = 0
const ROOM_STARTING = 1
const ROOM_ACTIVE = 2
const ROOM_ENDED = 3
// RoundPhase enum
const PHASE_DISCUSSION = 1
const PHASE_VOTING = 2
// PlayerStatus enum
const STATUS_INFECTED = 1
const STATUS_ELIMINATED = 2

const POOL_TICK_MS = 5_000
const GAME_TIMEOUT_MS = 20 * 60 * 1000 // safety cap on a single game
const CHAT_MIN_INTERVAL_MS = 15_000

// ── Zombie-themed chat lines bots send during discussion ──────────────────────
const CHAT_LINES = [
  "I'm definitely clean, check my commitment 🧪",
  'Something feels off about this round...',
  "I haven't seen anyone act suspicious yet.",
  'Who do we trust? Nobody, probably.',
  'The infected are among us — I can feel it.',
  'My symptoms are zero. Purely human here.',
  "Don't look at me like that.",
  "Let's eliminate someone who isn't talking.",
  'The plague spreads through silence.',
  "I'll survive this round. Probably.",
]
const randomLine = () => CHAT_LINES[Math.floor(Math.random() * CHAT_LINES.length)]

// ── Globals (set in main) ───────────────────────────────────────────────────────
let bots: BotWallet[] = []
let proofs: BotProof[] = []

// ── Per-participation state ─────────────────────────────────────────────────────
interface PlayState {
  bot: BotWallet
  proof: BotProof
  socket: Socket | null
  hasCommitted: boolean
  votedRound: number
  votedTargets: Set<string>
  lastChatAt: number
}

function mkState(index: number): PlayState {
  return {
    bot: bots[index],
    proof: proofs[index],
    socket: null,
    hasCommitted: false,
    votedRound: 0,
    votedTargets: new Set(),
    lastChatAt: 0,
  }
}

// ── Backend coordination ────────────────────────────────────────────────────────

interface BotJoinRequest { roomId: string; count: number }

async function postState(available: number, total: number): Promise<void> {
  try {
    await fetch(`${BACKEND_URL}/api/bots/state`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'x-bot-secret': BOT_RUNNER_SECRET },
      body: JSON.stringify({ available, total, maxStakeWei: BOT_MAX_STAKE_WEI.toString() }),
    })
  } catch {
    // Backend unreachable — bots keep running, availability just won't show.
  }
}

async function fetchRequests(): Promise<BotJoinRequest[]> {
  try {
    const r = await fetch(`${BACKEND_URL}/api/bots/requests`, {
      headers: { 'x-bot-secret': BOT_RUNNER_SECRET },
    })
    if (!r.ok) return []
    const j = (await r.json()) as { requests?: BotJoinRequest[] }
    return Array.isArray(j.requests) ? j.requests : []
  } catch {
    return []
  }
}

// ── Chat socket (best-effort presence + flavor) ─────────────────────────────────

function connectChatSocket(bot: BotWallet, roomId: bigint): Socket {
  const socket = io(BACKEND_URL, { transports: ['websocket'] })
  socket.on('connect', () => {
    socket.emit('join_room', { roomId: roomId.toString(), playerAddress: bot.address })
  })
  return socket
}

// ── Per-bot actions (idempotent, guarded) ───────────────────────────────────────

function commitRole(state: PlayState, roomId: bigint): void {
  if (state.hasCommitted) return
  state.hasCommitted = true
  void submitRoleCommitment(state.bot, roomId, state.proof.commitment, state.proof.proofHex)
    .catch(err => {
      state.hasCommitted = false // retry on the next poll tick
      console.warn(`[bot-${state.bot.index}] Commitment failed: ${err.message}`)
    })
}

/**
 * Vote once per round. Fair information model: a bot only uses its own role and
 * its own vote history. Infected bots prefer fresh targets (the patient zero's
 * vote doubles as the next infection target); clean bots vote at random.
 */
function castVoteForBot(
  state: PlayState,
  roomId: bigint,
  round: number,
  aliveAddrs: string[],
  ownInfected: boolean,
): void {
  if (state.votedRound >= round) return
  const self = state.bot.address.toLowerCase()
  const candidates = aliveAddrs.filter(a => a !== self)
  if (candidates.length === 0) return

  let pool = candidates
  if (ownInfected) {
    const fresh = candidates.filter(a => !state.votedTargets.has(a))
    if (fresh.length > 0) pool = fresh
  }
  const target = pool[Math.floor(Math.random() * pool.length)] as `0x${string}`

  state.votedRound = round
  void castVote(state.bot, roomId, target)
    .then(() => { state.votedTargets.add(target) })
    .catch(err => {
      const msg = err instanceof Error ? err.message : String(err)
      if (/AlreadyVoted/.test(msg)) { state.votedTargets.add(target); return }
      state.votedRound = round - 1
      console.warn(`[bot-${state.bot.index}] Vote failed: ${msg}`)
    })
}

function maybeChat(state: PlayState, roomId: bigint): void {
  const now = Date.now()
  if (now - state.lastChatAt < CHAT_MIN_INTERVAL_MS) return
  if (Math.random() > 0.4) return
  state.lastChatAt = now
  state.socket?.emit('chat_message', {
    roomId: roomId.toString(),
    playerAddress: state.bot.address,
    message: randomLine(),
  })
}

// ── Run a single game to completion, driven by chain state ───────────────────────

async function runChainDrivenGame(
  roomId: bigint,
  states: PlayState[],
  opts: { hostIndex?: number; maxPlayers?: number },
): Promise<void> {
  for (const s of states) s.socket = connectChatSocket(s.bot, roomId)

  await new Promise<void>(resolveGame => {
    let done = false
    let startSent = false

    const finish = () => {
      if (done) return
      done = true
      clearInterval(poll)
      clearTimeout(safety)
      for (const s of states) s.socket?.disconnect()
      resolveGame()
    }

    const poll = setInterval(async () => {
      try {
        const room = await getRoom(roomId)
        const status = Number(room.status)

        if (status === ROOM_ENDED) { finish(); return }

        if (status === ROOM_STARTING) {
          for (const s of states) commitRole(s, roomId)
          return
        }

        // Self-play host starts the game once the room is full.
        if (
          opts.hostIndex !== undefined &&
          !startSent &&
          status === ROOM_WAITING &&
          room.players.length >= (opts.maxPlayers ?? states.length)
        ) {
          startSent = true
          const host = states.find(s => s.bot.index === opts.hostIndex)
          host && void startGame(host.bot, roomId).catch(err => {
            startSent = false
            console.warn(`[bot-${opts.hostIndex}] startGame failed: ${err.message}`)
          })
          return
        }

        if (status === ROOM_ACTIVE) {
          const phase = Number(room.currentPhase)
          if (phase === PHASE_VOTING) {
            const round = Number(room.currentRound)
            const pending = states.filter(s => s.votedRound < round)
            if (pending.length > 0) {
              const roster = await getRoomStatuses(roomId)
              const alive = roster.filter(p => p.status !== STATUS_ELIMINATED).map(p => p.addr)
              for (const s of pending) {
                const me = roster.find(p => p.addr === s.bot.address.toLowerCase())
                if (!me || me.status === STATUS_ELIMINATED) { s.votedRound = round; continue }
                castVoteForBot(s, roomId, round, alive, me.status === STATUS_INFECTED)
              }
            }
          } else if (phase === PHASE_DISCUSSION) {
            for (const s of states) maybeChat(s, roomId)
          }
        }
      } catch {
        // Transient RPC error — retry on the next tick.
      }
    }, 4_000)

    const safety = setTimeout(finish, GAME_TIMEOUT_MS)
  })
}

// ── Game flavors ─────────────────────────────────────────────────────────────────

/** Self-play: bots create and fill their own room. */
async function selfPlay(indices: number[]): Promise<void> {
  const hostIndex = indices[0]
  await Promise.all(indices.map(i => ensureApproval(bots[i], STAKE_AMOUNT * 10n)))
  const roomId = await createRoom(bots[hostIndex], STAKE_AMOUNT, indices.length)
  for (const i of indices.slice(1)) {
    await joinRoom(bots[i], roomId)
    await sleep(1_200)
  }
  await runChainDrivenGame(roomId, indices.map(mkState), { hostIndex, maxPlayers: indices.length })
}

/** Join an existing human-hosted room (the human is host and starts the game). */
async function joinHumanRoom(roomId: bigint, indices: number[]): Promise<void> {
  const room = await getRoom(roomId)
  const stake = BigInt(room.config.stakeAmount)
  if (stake > BOT_MAX_STAKE_WEI) {
    console.warn(`[pool] skipping room ${roomId}: stake ${stake} exceeds cap ${BOT_MAX_STAKE_WEI}`)
    return
  }
  const joined: number[] = []
  for (const i of indices) {
    try {
      await ensureApproval(bots[i], stake)
      await joinRoom(bots[i], roomId)
      joined.push(i)
      await sleep(1_200)
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      console.warn(`[bot-${i}] could not join room ${roomId}: ${msg}`)
    }
  }
  if (joined.length === 0) return
  console.log(`[pool] ${joined.length} bot(s) joined human room #${roomId}`)
  await runChainDrivenGame(roomId, joined.map(mkState), {})
}

// ── Pool manager ──────────────────────────────────────────────────────────────

const busy: boolean[] = []
let allIdleSince = Date.now()

const freeIndices = () => bots.map((_, i) => i).filter(i => !busy[i])
const reserve = (idx: number[]) => idx.forEach(i => { busy[i] = true })
function release(idx: number[]): void {
  idx.forEach(i => { busy[i] = false })
  if (freeIndices().length === bots.length) allIdleSince = Date.now()
}

async function poolTick(): Promise<void> {
  // 1. Human demand first.
  const requests = await fetchRequests()
  for (const req of requests) {
    const free = freeIndices()
    if (free.length === 0) break
    const take = free.slice(0, Math.min(req.count, free.length))
    reserve(take)
    void joinHumanRoom(BigInt(req.roomId), take)
      .catch(err => console.warn(`[pool] human room ${req.roomId} failed: ${err.message}`))
      .finally(() => release(take))
  }

  // 2. Idle self-play fallback — only when the whole pool is free and quiet.
  if (
    !SELF_PLAY_DISABLED &&
    requests.length === 0 &&
    bots.length >= 4 &&
    freeIndices().length === bots.length &&
    Date.now() - allIdleSince >= SELF_PLAY_IDLE_MS
  ) {
    // Backpressure: createRoom reverts with TooManyActiveRooms once the contract
    // is at capacity. Skip quietly instead of burning gas on a doomed tx.
    if (await hasRoomCapacity()) {
      const take = freeIndices()
      reserve(take)
      console.log('[pool] no human demand — starting a self-play game')
      void selfPlay(take)
        .catch(err => console.warn(`[pool] self-play failed: ${err.message}`))
        .finally(() => release(take))
    } else {
      console.log('[pool] at active-room capacity — skipping self-play this tick')
    }
  }

  // 3. Heartbeat availability.
  await postState(freeIndices().length, bots.length)
}

// ── Utilities ─────────────────────────────────────────────────────────────────

const sleep = (ms: number) => new Promise<void>(r => setTimeout(r, ms))

// ── Main ──────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  console.log('\nZombie Plague Bot Pool')
  console.log('======================')
  console.log(`Backend: ${BACKEND_URL}`)
  console.log(`Network: ${process.env.NETWORK ?? 'testnet'}`)

  try {
    proofs = JSON.parse(await readFile(PROOFS_PATH, 'utf8')) as BotProof[]
    console.log(`Loaded ${proofs.length} pre-generated bot proof(s) from ${PROOFS_PATH}`)
  } catch {
    console.error(`\nFailed to load ${PROOFS_PATH}`)
    console.error('Run `npm run setup` first to generate bot proofs.\n')
    process.exit(1)
  }

  bots = buildBotWallets()
  if (proofs.length < bots.length) {
    console.error(`Proof count (${proofs.length}) < bot count (${bots.length}). Re-run setup.`)
    process.exit(1)
  }
  for (let i = 0; i < bots.length; i++) {
    if (proofs[i].address.toLowerCase() !== bots[i].address.toLowerCase()) {
      console.error(`Address mismatch at index ${i}: proof ${proofs[i].address} vs wallet ${bots[i].address}. Re-run setup.`)
      process.exit(1)
    }
    busy[i] = false
  }

  console.log('\nBot wallets:')
  for (const b of bots) console.log(`  Bot ${b.index + 1}: ${b.address}`)
  console.log(`\nMax human-room stake: ${BOT_MAX_STAKE_WEI} wei`)
  console.log(`Self-play after idle: ${SELF_PLAY_DISABLED ? 'DISABLED' : `${SELF_PLAY_IDLE_MS / 1000}s`}`)
  console.log('\nPool running. Waiting for human rooms / idle self-play...\n')

  // eslint-disable-next-line no-constant-condition
  while (true) {
    try {
      await poolTick()
    } catch (err) {
      console.warn(`[pool] tick error: ${err instanceof Error ? err.message : err}`)
    }
    await sleep(POOL_TICK_MS)
  }
}

main().catch(err => {
  console.error('Fatal:', err)
  process.exit(1)
})
