/**
 * runner.ts — Main bot game loop.
 *
 * Orchestrates N bot wallets playing Zombie Plague autonomously.
 *
 * Lifecycle per cycle:
 *   1. Bot[0] (host) creates a room
 *   2. All bots approve cUSD + join the room
 *   3. All bots connect to backend socket with their playerAddress
 *   4. When room reaches maxPlayers, Bot[0] calls startGame()
 *   5. On game_started: each bot submits their pre-generated role commitment
 *   6. On phase_changed → voting: each alive bot casts a vote
 *   7. On game_ended: disconnect sockets, wait CYCLE_DELAY_MS, repeat
 *
 * Requires: agents/data/bot-proofs.json (generated by `npm run setup`)
 */
import { readFile } from 'fs/promises'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import { io, Socket } from 'socket.io-client'
import { buildBotWallets, BACKEND_URL, STAKE_AMOUNT, CYCLE_DELAY_MS } from './config.js'
import {
  ensureApproval,
  createRoom,
  joinRoom,
  startGame,
  submitRoleCommitment,
  castVote,
  getPlayerStatus,
} from './chain.js'
import type { BotWallet } from './config.js'
import type { BotProof } from './setup.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const PROOFS_PATH = resolve(__dirname, '../data/bot-proofs.json')

// Phase numbers from the contract
const PHASE_VOTING = 2

// Player status numbers from the contract
const STATUS_ELIMINATED = 2

// ── Zombie-themed chat lines bots send during discussion ──────────────────────
const CHAT_LINES = [
  "I'm definitely clean, check my commitment 🧪",
  'Something feels off about this round...',
  "I haven't seen anyone act suspicious yet.",
  'Who do we trust? Nobody, probably.',
  "The infected are among us — I can feel it.",
  'My symptoms are zero. Purely human here.',
  "Don't look at me like that.",
  "Let's eliminate someone who isn't talking.",
  'The plague spreads through silence.',
  "I'll survive this round. Probably.",
]

function randomLine(): string {
  return CHAT_LINES[Math.floor(Math.random() * CHAT_LINES.length)]
}

// ── Socket helpers ────────────────────────────────────────────────────────────

interface GameEvent {
  type: string
  roomId: string
  payload: Record<string, unknown>
  timestamp: number
}

interface RoomSnapshot {
  roomId: string
  room: {
    status: number
    currentPhase: number
    players: string[]
  }
  players: Array<{ addr: string; status: number; hasVotedThisRound: boolean }>
}

function connectBot(
  bot: BotWallet,
  roomId: bigint,
  handlers: {
    onGameStarted: () => void
    onPhaseChanged: (phase: number) => void
    onInfectionAssigned: () => void
    onGameEnded: () => void
    onSnapshot: (snap: RoomSnapshot) => void
  },
): Socket {
  const socket = io(BACKEND_URL, { transports: ['websocket'] })

  socket.on('connect', () => {
    console.log(`[bot-${bot.index}] Socket connected (${socket.id})`)
    socket.emit('join_room', {
      roomId: roomId.toString(),
      playerAddress: bot.address,
    })
  })

  socket.on('game_event', (event: GameEvent) => {
    if (event.roomId !== roomId.toString()) return

    switch (event.type) {
      case 'game_started':
        handlers.onGameStarted()
        break
      case 'phase_changed':
        handlers.onPhaseChanged(Number(event.payload.phase))
        break
      case 'infection_assigned':
        // Only received by the infected bot's own socket
        handlers.onInfectionAssigned()
        break
      case 'game_ended':
        handlers.onGameEnded()
        break
    }
  })

  socket.on('room_snapshot', (snap: RoomSnapshot) => {
    if (snap.roomId === roomId.toString()) {
      handlers.onSnapshot(snap)
    }
  })

  socket.on('disconnect', (reason: string) => {
    console.log(`[bot-${bot.index}] Socket disconnected: ${reason}`)
  })

  socket.on('connect_error', (err: Error) => {
    console.warn(`[bot-${bot.index}] Socket connect error: ${err.message}`)
  })

  return socket
}

// ── Per-bot state ─────────────────────────────────────────────────────────────

interface BotState {
  bot: BotWallet
  proof: BotProof
  socket: Socket | null
  isInfected: boolean
  hasCommitted: boolean
  hasVotedThisRound: boolean
  alivePlayers: string[] // updated from room snapshots
}

// ── Game cycle ────────────────────────────────────────────────────────────────

async function runCycle(bots: BotWallet[], proofs: BotProof[]): Promise<void> {
  const host = bots[0]
  const maxPlayers = bots.length

  console.log(`\n${'='.repeat(60)}`)
  console.log(`Starting cycle with ${maxPlayers} bots`)
  console.log(`${'='.repeat(60)}`)

  // 1. Ensure all bots have approved cUSD
  console.log('\n[setup] Approving cUSD for all bots...')
  await Promise.all(bots.map(bot => ensureApproval(bot, STAKE_AMOUNT * 10n)))

  // 2. Host creates the room
  console.log('\n[setup] Creating room...')
  const roomId = await createRoom(host, STAKE_AMOUNT, maxPlayers)

  // 3. Other bots join (staggered to avoid nonce conflicts)
  console.log('\n[setup] Joining room...')
  for (let i = 1; i < bots.length; i++) {
    await joinRoom(bots[i], roomId)
    await sleep(1500)
  }

  // 4. Connect all bots to socket and set up state
  const states: BotState[] = bots.map((bot, i) => ({
    bot,
    proof: proofs[i],
    socket: null,
    isInfected: false,
    hasCommitted: false,
    hasVotedThisRound: false,
    alivePlayers: [],
  }))

  // Track resolved game end
  let gameEnded = false
  const gameEndedPromise = new Promise<void>(resolve => {
    // Resolved when the first game_ended event arrives
    const checkDone = () => {
      if (gameEnded) resolve()
    }

    for (const state of states) {
      state.socket = connectBot(state.bot, roomId, {
        onGameStarted: () => {
          if (state.hasCommitted) return
          state.hasCommitted = true
          void submitRoleCommitment(
            state.bot,
            roomId,
            state.proof.commitment,
            state.proof.proofHex,
          ).catch(err => {
            console.warn(`[bot-${state.bot.index}] Commitment failed: ${err.message}`)
          })
        },

        onInfectionAssigned: () => {
          state.isInfected = true
          console.log(`[bot-${state.bot.index}] *** INFECTED (patient zero) ***`)
        },

        onPhaseChanged: (phase: number) => {
          if (phase === PHASE_VOTING && !state.hasVotedThisRound) {
            state.hasVotedThisRound = true
            void castVoteForBot(state, roomId).catch(err => {
              console.warn(`[bot-${state.bot.index}] Vote failed: ${err.message}`)
            })
          }
          // Reset vote flag at the start of the next non-voting phase
          if (phase !== PHASE_VOTING) {
            state.hasVotedThisRound = false
          }
        },

        onGameEnded: () => {
          gameEnded = true
          checkDone()
        },

        onSnapshot: (snap: RoomSnapshot) => {
          // Track alive players from snapshots
          const alive = snap.players
            .filter(p => p.status !== STATUS_ELIMINATED)
            .map(p => p.addr.toLowerCase())
          state.alivePlayers = alive

          // Host: start game when room is full
          if (
            state.bot.index === 0 &&
            snap.room.status === 0 && // waiting
            snap.room.players.length >= maxPlayers
          ) {
            void startGame(state.bot, roomId).catch(err => {
              console.warn(`[bot-0] startGame failed: ${err.message}`)
            })
          }

          // Send a chat message during discussion phase (occasional)
          if (snap.room.currentPhase === 1 && Math.random() < 0.3) {
            state.socket?.emit('chat_message', {
              roomId: roomId.toString(),
              playerAddress: state.bot.address,
              message: randomLine(),
            })
          }
        },
      })
    }
  })

  // 5. Wait for game to end (with a safety timeout)
  const GAME_TIMEOUT_MS = 20 * 60 * 1000 // 20 minutes max
  await Promise.race([gameEndedPromise, sleep(GAME_TIMEOUT_MS)])

  // 6. Disconnect all sockets
  for (const state of states) {
    state.socket?.disconnect()
  }

  console.log(`\n[cycle] Game ended. Waiting ${CYCLE_DELAY_MS / 1000}s before next cycle...`)
}

// ── Vote strategy ─────────────────────────────────────────────────────────────

async function castVoteForBot(state: BotState, roomId: bigint): Promise<void> {
  // Pick a random alive player that isn't this bot
  const candidates = state.alivePlayers.filter(
    addr => addr !== state.bot.address.toLowerCase(),
  )

  if (candidates.length === 0) {
    console.log(`[bot-${state.bot.index}] No candidates to vote for — skipping`)
    return
  }

  // Infected bots prefer to vote for clean players (random selection here,
  // real strategy could be smarter). Clean bots vote randomly.
  const target = candidates[Math.floor(Math.random() * candidates.length)] as `0x${string}`

  await castVote(state.bot, roomId, target)
}

// ── Utilities ─────────────────────────────────────────────────────────────────

function sleep(ms: number): Promise<void> {
  return new Promise(res => setTimeout(res, ms))
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  console.log('\nZombie Plague Bot Runner')
  console.log('========================')
  console.log(`Backend: ${BACKEND_URL}`)
  console.log(`Network: ${process.env.NETWORK ?? 'testnet'}`)

  // Load pre-generated proofs
  let proofs: BotProof[]
  try {
    const raw = await readFile(PROOFS_PATH, 'utf8')
    proofs = JSON.parse(raw) as BotProof[]
    console.log(`Loaded ${proofs.length} pre-generated bot proof(s) from ${PROOFS_PATH}`)
  } catch {
    console.error(`\nFailed to load ${PROOFS_PATH}`)
    console.error('Run `npm run setup` first to generate bot proofs.\n')
    process.exit(1)
  }

  const bots = buildBotWallets()

  if (proofs.length < bots.length) {
    console.error(
      `Proof count (${proofs.length}) < bot count (${bots.length}). Re-run setup.`,
    )
    process.exit(1)
  }

  // Verify proof addresses match wallet addresses
  for (let i = 0; i < bots.length; i++) {
    if (proofs[i].address.toLowerCase() !== bots[i].address.toLowerCase()) {
      console.error(
        `Address mismatch at index ${i}: proof has ${proofs[i].address}, ` +
          `wallet is ${bots[i].address}. Re-run setup.`,
      )
      process.exit(1)
    }
  }

  console.log('\nBot wallets:')
  for (const b of bots) console.log(`  Bot ${b.index + 1}: ${b.address}`)

  // Main loop
  let cycle = 0
  while (true) {
    cycle++
    console.log(`\n[runner] Cycle ${cycle}`)
    try {
      await runCycle(bots, proofs)
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      console.error(`[runner] Cycle ${cycle} error: ${msg}`)
      console.log(`[runner] Retrying in ${CYCLE_DELAY_MS / 1000}s...`)
    }
    await sleep(CYCLE_DELAY_MS)
  }
}

main().catch(err => {
  console.error('Fatal:', err)
  process.exit(1)
})
