/**
 * zk.ts — ZK utilities for bot agents.
 *
 * Commitment:  poseidon2(role, secret)  — computed via Barretenberg WASM
 * Witness:     generated via @noir-lang/noir_js  (Noir circuit executor)
 * Proof:       generated by calling POST /api/prove on the backend
 *              (uses the native `bb` CLI which handles MsgPackCompact ACIR)
 */
import { Barretenberg, Fr } from '@aztec/bb.js'
import { Noir } from '@noir-lang/noir_js'
import { readFile, mkdir } from 'fs/promises'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))

// Circuit artifact relative to repo root
const CIRCUIT_DIR = resolve(__dirname, '../../zk/target')

// BN254 scalar field modulus — secrets must be reduced modulo this
export const BN254_R =
  21888242871839275222246405745257275088548364400416034343698204186575808495617n

// ── Barretenberg singleton ────────────────────────────────────────────────────

let _bb: Barretenberg | null = null

async function getBB(): Promise<Barretenberg> {
  if (!_bb) {
    _bb = await Barretenberg.new({ threads: 1 })
  }
  return _bb
}

// ── Circuit singleton ─────────────────────────────────────────────────────────

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let _circuit: any = null

async function getRoleCommitmentCircuit(): Promise<unknown> {
  if (!_circuit) {
    const json = await readFile(resolve(CIRCUIT_DIR, 'role_commitment.json'), 'utf8')
    _circuit = JSON.parse(json)
  }
  return _circuit
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function toField(v: bigint): string {
  return `0x${v.toString(16).padStart(64, '0')}`
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Compute the role commitment: poseidon2_permutation([role, secret, 0, 0])[0]
 * This must match the Noir circuit exactly.
 */
export async function computeCommitment(role: bigint, secret: bigint): Promise<bigint> {
  const bb = await getBB()
  const res = await bb.poseidon2Permutation([new Fr(role), new Fr(secret), Fr.ZERO, Fr.ZERO])
  return BigInt(res[0].toString())
}

/**
 * Generate a Noir witness for the role_commitment circuit.
 */
export async function generateRoleWitness(
  role: bigint,
  secret: bigint,
  commitment: bigint,
): Promise<Uint8Array> {
  const circuit = await getRoleCommitmentCircuit()
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const noir = new Noir(circuit as any)
  const { witness } = await noir.execute({
    commitment: toField(commitment),
    role: toField(role),
    secret: toField(secret),
  })
  return witness
}

/**
 * Send a compressed witness to the backend /api/prove endpoint and
 * return the 0x-prefixed proof hex string.
 */
export async function getProofFromBackend(
  witness: Uint8Array,
  backendUrl: string,
): Promise<`0x${string}`> {
  const witnessBase64 = Buffer.from(witness).toString('base64')

  const resp = await fetch(`${backendUrl}/api/prove`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ circuitId: 'role_commitment', witnessBase64 }),
  })

  if (!resp.ok) {
    const body = await resp.json().catch(() => ({})) as { error?: string; detail?: string }
    throw new Error(body.detail ?? body.error ?? `Proof generation failed: HTTP ${resp.status}`)
  }

  const { proofHex } = (await resp.json()) as { proofHex: string }
  return (proofHex.startsWith('0x') ? proofHex : `0x${proofHex}`) as `0x${string}`
}

/**
 * Full pipeline: commitment + witness + proof.
 * Returns the data needed for submitRoleCommitment().
 */
export async function generateRoleProof(
  role: 0n | 1n,
  secret: bigint,
  backendUrl: string,
): Promise<{ commitment: `0x${string}`; proofHex: `0x${string}` }> {
  const commitment = await computeCommitment(role, secret)
  const commitmentHex = toField(commitment) as `0x${string}`

  const witness = await generateRoleWitness(role, secret, commitment)
  const proofHex = await getProofFromBackend(witness, backendUrl)

  return { commitment: commitmentHex, proofHex }
}

export { toField }
