name: ci-disabled

on:
  workflow_dispatch:

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: CI disabled
        run: echo "CI is intentionally disabled for private development."
