// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title IZKVerifier
 * @notice Interface for on-chain ZK proof verification.
 *
 *         The production implementation is generated by Noir's Solidity Groth16
 *         verifier output. To generate it:
 *
 *           cd zk/circuits
 *           nargo prove                 # compile + generate proof artifacts
 *           nargo codegen-verifier      # writes Verifier.sol (Groth16, Solidity)
 *
 *         Deploy the generated Verifier.sol and point PlagueGame at it:
 *           game.setZKVerifier(address(verifier));
 *
 * ── Circuits ──────────────────────────────────────────────────────────────────
 *
 *  role_commitment.nr
 *    Private inputs : role, secret
 *    Public outputs : commitment = Poseidon(role, secret)
 *    Constraint     : none beyond the commitment binding
 *
 *  innocence_proof.nr
 *    Private inputs : role, secret, room_id, round_number
 *    Public outputs : commitment = Poseidon(role, secret)
 *                     nullifier  = Poseidon(secret, room_id, round_number)
 *    Constraint     : role == ROLE_CLEAN (0) — infected players cannot satisfy this
 */
interface IZKVerifier {
    /**
     * @param commitment  Poseidon(role, secret) as submitted at startGame.
     * @param proof       Groth16 proof bytes produced by nargo prove.
     */
    function verifyRoleCommitment(
        bytes32 commitment,
        bytes calldata proof
    ) external view returns (bool);

    /**
     * @param commitment  Poseidon(role, secret) — must match the stored commitment.
     * @param nullifier   Poseidon(secret, roomId, round) — uniquely prevents replay.
     * @param proof       Groth16 proof bytes produced by nargo prove.
     */
    function verifyInnocenceProof(
        bytes32 commitment,
        bytes32 nullifier,
        bytes calldata proof
    ) external view returns (bool);
}

/**
 * @title ZKVerifier
 * @notice Development-only stub that accepts all proofs.
 *
 *         ⚠️  NEVER deploy with bypassEnabled = true to a production network.
 *
 *         Replace this contract with the Noir-generated Groth16 Verifier.sol
 *         before mainnet deployment, then call `setBypass(false)` or simply
 *         do not deploy this stub at all.
 */
contract ZKVerifier is IZKVerifier {
    /// @notice When true all proofs are accepted unconditionally (dev/test only).
    bool public bypassEnabled;

    address public owner;

    event BypassSet(bool enabled);

    constructor(bool _bypassEnabled) {
        owner          = msg.sender;
        bypassEnabled  = _bypassEnabled;
    }

    function setBypass(bool enabled) external {
        require(msg.sender == owner, "ZKVerifier: not owner");
        bypassEnabled = enabled;
        emit BypassSet(enabled);
    }

    function verifyRoleCommitment(
        bytes32, /*commitment*/
        bytes calldata /*proof*/
    ) external view override returns (bool) {
        return bypassEnabled;
    }

    function verifyInnocenceProof(
        bytes32, /*commitment*/
        bytes32, /*nullifier*/
        bytes calldata /*proof*/
    ) external view override returns (bool) {
        return bypassEnabled;
    }
}
